kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    app: integral
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
